version: '3'
services:
  app:
    container_name: alarm-panel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7070:7070
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
